spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://47.100.187.237:3306/jdbc
    type: com.alibaba.druid.pool.DruidDataSource

    ##Druid\u7684\u5176\u4ED6\u914D\u7F6E
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    ##\u521D\u59CB\u5316sql\u8BED\u53E5,\u5728\u5EFA\u597D\u8868\u4E4B\u540E\uFF0C\u5C06\u4E0B\u9762\u7684\u6CE8\u91CA\u6389\uFF0C\u5426\u5219\u5728\u91CD\u542F\u5E94\u7528\u65F6\uFF0C\u4F1A\u518D\u6B21\u91CD\u65B0\u5EFA\u8868\uFF0C\u5C06\u4E4B\u524D\u8868\u4E2D\u5185\u5BB9\u8986\u76D6\uFF01\uFF01
#    initialization-mode: always
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
